# Generated by Django 3.2.4 on 2021-06-25 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_ssuapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='body',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='pub_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='writer',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
